version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8

workflows:
  build-and-deploy:
    jobs:
      # develop環境へのデプロイ
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: develop
          repo: "njss_kamuy-dev/laravel-sample"
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only: develop
          requires:
            - aws-ecr/build-and-push-image
          service-name: "njss-kamuy-dev-web"
          family: "njss_kamuy-dev-web"
          cluster-name: "njss_kamuy-dev-web"
          container-image-name-updates: "container=LaravelSample,tag=${CIRCLE_TAG}"