version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@0.0.7
  aws-ecr: circleci/aws-ecr@3.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "790392395917.dkr.ecr.ap-northeast-1.amazonaws.com"
          repo: 'njss_kamuy-dev/laravel-sample'
          tag: '${CIRCLE_SHA1}'