version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@0.0.2
  aws-ecr: circleci/aws-ecr@3.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: 'njss_kamuy-dev/laravel-sample'
          tag: '${CIRCLE_SHA1}'