version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8

workflows:
  environment:
    ECR_REPO_NAME: "njss_kamuy-dev/laravel-sample"
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${ECR_REPO_NAME}
          region: AWS_DEFAULT_REGION
          tag: CIRCLE_SHA1
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_DEFAULT_REGION}
          service-name: "njss-kamuy-dev-web"
          family: "njss_kamuy-dev-web"
          cluster-name: "njss_kamuy-dev-web"
          container-image-name-updates: "container=LaravelSample,image-and-tag=${AWS_ECR_ACCOUNT_URL}/njss_kamuy-dev/laravel-sample:${CIRCLE_SHA1}"