version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.7
  aws-ecr: circleci/aws-ecr@3.1.0

jobs:
  build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - run: sudo apt update